Traceback (most recent call last):
  File "/home/alex/Bureau/llm/blablateurbinaire/mlp_lm.py", line 101, in <module>
    run()
  File "/home/alex/Bureau/llm/blablateurbinaire/mlp_lm.py", line 97, in run
    objective(config, True)
  File "/home/alex/Bureau/llm/blablateurbinaire/mlp_lm.py", line 24, in objective
    lr = config['lr']
         ~~~~~~^^^^^^
KeyError: 'lr'